### ISSUE TITLE
Milestone 01 feedback

### ISSUE THREAD

**Issue by Pall-v** [UBC-MDS/AudioFilters_py#26]
Pasted from [https://github.com/UBC-MDS/AudioFilters_R/issues/9](https://github.com/UBC-MDS/AudioFilters_R/issues/9 ):
Hello,

Thanks for the milestone 01 submission. You did a really good job. I just have some comments below,

- You did a good job on using `roxygen2` for generating documentation files.
- [x] * You should specify at what format the user should input the files.
- [x] * You should at a test of `expect_error()` when the `input_signal` is in a wrong format.
- [x] * You should at a test in `test_add_reverb.R` of `expect_error()` when the `type` is in a wrong format.
- [x] * You should at a test in `test_change_speed.R` of `expect_error()` when the `rate` is in a wrong format.
- [x] * You should at a test in `test_high_pass_filter.R` of `expect_error()` when the `cutoff_frequency` is in a wrong format.
Thank you!

**Comment by mchiriboga** [comment]
I'm adding tests for expected errors for `type`, `rate` and `cutoff_frequency` (items 3,4 and 5). For item 2, I added a step to convert the `input_signal` to `float` if the one passed to the functions is of type int. I'm also adding an error for when it's not of a valid type. I'll submit a PR soon.
